### ISSUE TITLE
Oracle.ManagedDataAccess

### ISSUE THREAD

**Issue by wahmedswl** [LinqDan/oracleclientcore#1]
Hi,
   Oracle is moving toward fully managed client, i guess this should still require Oracle Client installation via xcopy or full installation on linux? Managed version doesn't need anything, just reference and start using it without any dependency nor x86/x64 stuff.

Thanks

**Comment by alexishida** [comment]
I have this problem on linux. 
Is it mandatory to use Linux Oracle Client?
How i solve this dependency?

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'oci': The specified module could not be found.
(Exception from HRESULT: 0x8007007E)
  at System.Data.OracleClient.Oci.OciCalls.OciNativeCalls.OCIEnvCreate(IntPtr& envhpp, OciEnvironmentMode mode, IntPtr ctxp, IntPtr malocfp, IntPtr ralocfp, IntPtr mfreep, Int32 xtramem_sz, IntPtr usrmempp)
  at System.Data.OracleClient.Oci.OciEnvironmentHandle..ctor(OciEnvironmentMode mode)
  at System.Data.OracleClient.Oci.OciGlue.CreateConnection(OracleConnectionInfo conInfo)
  at System.Data.OracleClient.OracleConnectionPoolManager.CreateConnection(OracleConnectionInfo info)

**Comment by steve-gray** [comment]
@alexishida - You'll find that inside OciCalls.cs there's a a toggle that needs to be platform-dynamic that isnt, and it's using the Windows names by default. I had a pretty crappy time trying to get this working on OSX until I realised, as I'd been trying to figure out why OCI/Instaclient wasn't working.

Change the #define - but also look around for the IsUnix call - you need to set the Unix flag or you'll bomb out on a Kernel32 hook as well from Windows, whereas libc does the work on *nix/OSX.

**Comment by aldovrando-oliveira** [comment]
HI,

I have this problem on linux (Ubuntu 16.04)

   System.DllNotFoundException: Unable to load DLL 'libclntsh.so': The specified module could not be found.

dotnet --info
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.4

can you help me?

**Comment by tomasvarg** [comment]
@aldovrando-oliveira check the real file name of the libclntsh shared library on your system (distributed with an oracle package), eventualy link the actual name to "libclntsh.so" if it's different (for example mine was "libclntsh.so.11.1" in the "/usr/lib/oracle/product/11.2.0/xe/lib" directory, but I'm on ArchLinux). Furthermore, you might need to run "ldconfig -v" as root, if it's not enough still, check your system's doc on setting $LD_LIBRARY_PATH and set it to the Oracle's lib directory.
